### ISSUE TITLE
mauvaise recette pour le fabricator : steel

### ISSUE THREAD

**Issue by guitehub** [lucasriondel/icarus-resource-calculator#2]
**Describe the bug**
fabricator affiche "Steel Ingot * 8"
alors qu'il n'y en a pas besoin

**Screenshots**
![image](https://user-images.githubusercontent.com/10271201/212552809-24e49780-6734-4ea6-a371-c7258293bd75.png)

**Additional context**
le J c le S

**Comment by gazreyn** [comment]
I believe this issue can be closed as it was resolved and merged
https://github.com/lucasriondel/icarus-resource-calculator/commit/40f23e4e2c4c35d49ec2d6cbf1d6ccec2fd90654
