### ISSUE TITLE
[missing-item]

### ISSUE THREAD

**Issue by lildarryl024** [lucasriondel/icarus-resource-calculator#3]
Cement Mixer recipie calculates 50x wood but should be 50x refined wood.

**Comment by lucasriondel** [comment]
@lildarryl024 i've fixed the issue. it should be working properly now. 

just so you know, this calculator is no longer maintained. 

if you want to edit the existing recipes, you can [check this file which contain every recipe](https://github.com/lucasriondel/icarus-resource-calculator/blob/main/data/craftables.json).

you can make modifications and then propose them, i will be happy to merge them. 

have a good day !
